[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gol_marketplace = "CEjEmwBAGJxmxA8T3W17yjZDVzXX5xrcW9LwpL3Y3Ba9"

[registry]
url = "https://devnet.sonic.game"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
